<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Traninig_Managment_system</RootNamespace>
    <UserSecretsId>af0b85f7-f315-4ceb-aef2-8e9c2aad0842</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Company\**" />
    <Compile Remove="Areas\Instractor\**" />
    <Compile Remove="Areas\Manger\**" />
    <Content Remove="Areas\Company\**" />
    <Content Remove="Areas\Instractor\**" />
    <Content Remove="Areas\Manger\**" />
    <EmbeddedResource Remove="Areas\Company\**" />
    <EmbeddedResource Remove="Areas\Instractor\**" />
    <EmbeddedResource Remove="Areas\Manger\**" />
    <None Remove="Areas\Company\**" />
    <None Remove="Areas\Instractor\**" />
    <None Remove="Areas\Manger\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Areas\Company\Controllers\CategoryController.cs" />
    <Compile Include="Areas\Company\Controllers\CourseController.cs" />
    <Compile Include="Areas\Company\Controllers\EmployeeController.cs" />
    <Compile Include="Areas\Company\Controllers\HomeController.cs" />
    <Compile Include="Areas\Company\Controllers\InstractorController.cs" />
    <Compile Include="Areas\Instractor\Controllers\HomeController.cs" />
    <Compile Include="Areas\Instractor\Controllers\InstructorChaptersController.cs" />
    <Compile Include="Areas\Instractor\Controllers\InstructorExamsController.cs" />
    <Compile Include="Areas\Instractor\Controllers\InstructorLessonsController.cs" />
    <Compile Include="Areas\Instractor\Controllers\InstructorProgressController.cs" />
    <Compile Include="Areas\Manger\Controllers\DashBoardController.cs" />
    <Compile Include="Areas\Manger\Controllers\PlanController.cs" />
    <Compile Include="Areas\Manger\Controllers\CompaniesController.cs" />
  </ItemGroup>

	<ItemGroup>
		
		<PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
		
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.5" />
		
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
		
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Traninig-Managment-system.BLL\Traninig-Managment-system.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Home\Index.cshtml" />
    <Content Include="Areas\Company\Views\_ViewImports.cshtml" />
    <Content Include="Areas\Company\Views\_ViewStart.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Employee\Create.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Employee\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Employee\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Category\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Category\Create.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Category\Edit.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Course\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Course\Create.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Course\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Course\Edit.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Category\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Instractor\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Instractor\Create.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Instractor\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Company\Views\Employee\AssignCourse.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Instractor\Views\_ViewImports.cshtml" />
    <Content Include="Areas\Instractor\Views\_ViewStart.cshtml" />
    <Content Include="Areas\Instractor\Views\Home\DashBoard.cshtml" />
    <Content Include="Areas\Instractor\Views\Home\Details.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorChapters\Create.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorChapters\Edit.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorLessons\CreateLessons.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorLessons\EditLessons.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorProgress\Index.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorProgress\Details.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorExams\Create.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorExams\Edit.cshtml" />
    <Content Include="Areas\Instractor\Views\InstructorExams\_ExamFormFields.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Areas\Manger\Views\_ViewImports.cshtml" />
    <Content Include="Areas\Manger\Views\_ViewStart.cshtml" />
    <Content Include="Areas\Manger\Views\DashBoard\Index.cshtml" />
    <Content Include="Areas\Manger\Views\DashBoard\ChatHub.cshtml" />
    <Content Include="Areas\Manger\Views\Plan\Index.cshtml" />
    <Content Include="Areas\Manger\Views\Plan\Create.cshtml" />
    <Content Include="Areas\Manger\Views\Plan\Edit.cshtml" />
    <Content Include="Areas\Manger\Views\Plan\Details.cshtml" />
    <Content Include="Areas\Manger\Views\Plan\_PlanForm.cshtml" />
    <Content Include="Areas\Manger\Views\Companies\Index.cshtml" />
    <Content Include="Areas\Manger\Views\Companies\Details.cshtml" />
  </ItemGroup>

</Project>
